"""Generate `text/replay`'s targets: the backbone's own answers to the selected prompts.

    GPU=1 src/generalist/tools/launch/run_py.sh src/generalist/tools/replay/generate.py \
        --version v1 --limit 600 --out-name pilot          # the pilot
    GPU=4 src/generalist/tools/launch/run_py.sh src/generalist/tools/replay/generate.py \
        --version v1 --gpus 4                               # the whole set
    src/generalist/tools/launch/run_py.sh src/generalist/tools/replay/generate.py \
        --version v1 --summarise                            # CPU: rates and lengths

Reads ``results/replay/<version>/prompts.jsonl`` (`tools/replay/prompts.py`) and
writes one JSONL per shard under ``answers/``, one row per sampled answer.

**The teacher is the backbone, exactly.** On a single-node graph every structural
bias is identically zero (Property 2), so the trunk with its adapter off *is*
`Llama-3.2-1B-Instruct`, and sampling from the plain HF model on the **same token
ids** samples from the distribution replay is meant to hold the trunk to. The
ids are the build's: `molecules/data.py::CHAT_FORMAT`'s user turn and open
assistant turn, with no ``<|begin_of_text|>`` and no system turn — the same two
departures from the stock template every training example makes. A prompt
spelled differently here would distil an answer to a question the trunk is never
asked.

**Sampled, not greedy.** Greedy decoding at 1B loops, and a replay set of loops
teaches loops. The backbone's own `generation_config` samples at temperature
0.6 and top-p 0.9; 0.7 is a shade warmer, so three samples of one prompt differ
by more than a word while staying near its mode.

**Only terminated answers are targets.** An answer that reaches
:data:`MAX_NEW_TOKENS` without ``<|eot_id|>`` is kept in the file, flagged, and
never trained on: the trunk supervises the terminator, and an unterminated target
would teach it to stop mid-sentence. The cap is 768 because the text task's node
is 1,024 tokens and a prompt may take 256 of them.

Sampling is seeded per shard and batch, so a rerun on the same hardware and
library versions reproduces the file; across either it does not, which is why the
answers are generated once and versioned rather than regenerated by a build.
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import subprocess
import sys
import time

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
sys.path.insert(0, REPO)

OUT_ROOT = os.path.join(REPO, "src", "generalist", "results", "replay")
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
MAX_NEW_TOKENS = 768
TEMPERATURE = 0.7
TOP_P = 0.9
#: Sequences per `generate` call. The KV cache at 1B is ~32 KB a token (16 layers,
#: 8 KV heads of 64, bf16), so 512 sequences of 1,024 tokens is ~16 GB.
SEQUENCES_PER_BATCH = 512


def read_prompts(version_dir: str) -> list:
    with open(os.path.join(version_dir, "prompts.jsonl")) as fh:
        return [json.loads(line) for line in fh]


def prompt_ids(tokenizer, text: str) -> list:
    """The prompt as the build writes it: user turn, open assistant turn, no BOS."""
    from src.experiments.molecules.data import prompt_format

    fmt = prompt_format("chat", MODEL_NAME)
    return tokenizer(f"{fmt.question(text)}{fmt.answer_prefix}",
                     add_special_tokens=False)["input_ids"]


def done_ids(path: str) -> set:
    if not os.path.exists(path):
        return set()
    out = set()
    with open(path) as fh:
        for line in fh:
            try:
                out.add(json.loads(line)["id"])
            except (json.JSONDecodeError, KeyError):
                continue            # a torn last line from a killed job
    return out


def run_shard(args) -> None:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    version_dir = os.path.join(args.out_root, args.version)
    prompts = read_prompts(version_dir)
    if args.limit:
        # A pilot draws across the whole file rather than its head, which is
        # sorted by id and so already random, but stratified is the honest word
        # for what a fixed stride gives.
        stride = max(1, len(prompts) // args.limit)
        prompts = prompts[::stride][:args.limit]
    prompts = prompts[args.shard::args.num_shards]

    out_dir = os.path.join(version_dir, args.out_name)
    os.makedirs(out_dir, exist_ok=True)
    # What the adapter checks a run's backbone and format against: a replay set
    # is a property of the teacher, and training a different backbone on it
    # would distil one model's answers into another.
    record = os.path.join(out_dir, "generation.json")
    if not os.path.exists(record):
        import transformers

        with open(record, "w") as fh:
            json.dump({"model_name": MODEL_NAME, "prompt_style": "chat",
                       "temperature": args.temperature, "top_p": args.top_p,
                       "max_new_tokens": args.max_new_tokens, "seed": args.seed,
                       "sequences_per_batch": args.sequences_per_batch,
                       "limit": args.limit, "torch": torch.__version__,
                       "transformers": transformers.__version__}, fh, indent=1)
    path = os.path.join(out_dir, f"shard{args.shard:02d}.jsonl")
    finished = done_ids(path)
    todo = [p for p in prompts if p["id"] not in finished]
    print(f"[shard {args.shard}] {len(prompts)} prompts, {len(finished)} done, "
          f"{len(todo)} to go -> {path}", flush=True)
    if not todo:
        return

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    tokenizer.padding_side = "left"
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        pad_id = tokenizer.convert_tokens_to_ids("<|finetune_right_pad_id|>")
    eot_id = tokenizer.convert_tokens_to_ids("<|eot_id|>")
    eos_ids = sorted({eot_id, tokenizer.convert_tokens_to_ids("<|end_of_text|>"),
                      tokenizer.convert_tokens_to_ids("<|eom_id|>")})
    special = set(tokenizer.all_special_ids) | set(range(128000, 128256))

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME, torch_dtype=torch.bfloat16, attn_implementation="sdpa").cuda()
    model.eval()

    for p in todo:
        p["_ids"] = prompt_ids(tokenizer, p["text"])
    # Grouped by (samples, length) so a batch pads little and every row in it
    # asks for the same number of return sequences.
    todo.sort(key=lambda p: (p["samples"], len(p["_ids"])))

    batches, current, current_seqs = [], [], 0
    for p in todo:
        if current and (current[0]["samples"] != p["samples"]
                        or current_seqs + p["samples"] > args.sequences_per_batch):
            batches.append(current)
            current, current_seqs = [], 0
        current.append(p)
        current_seqs += p["samples"]
    if current:
        batches.append(current)

    started, seqs_done, tokens_done = time.time(), 0, 0
    with open(path, "a") as fh:
        for b, batch in enumerate(batches):
            k = batch[0]["samples"]
            width = max(len(p["_ids"]) for p in batch)
            input_ids = torch.full((len(batch), width), pad_id, dtype=torch.long)
            attention = torch.zeros((len(batch), width), dtype=torch.long)
            for i, p in enumerate(batch):
                ids = p["_ids"]
                input_ids[i, width - len(ids):] = torch.tensor(ids)
                attention[i, width - len(ids):] = 1
            torch.manual_seed(hash((args.seed, args.shard, b)) & 0x7FFFFFFF)
            with torch.no_grad():
                generated = model.generate(
                    input_ids=input_ids.cuda(), attention_mask=attention.cuda(),
                    do_sample=True, temperature=args.temperature, top_p=args.top_p,
                    max_new_tokens=args.max_new_tokens, num_return_sequences=k,
                    eos_token_id=eos_ids, pad_token_id=pad_id)
            fresh = generated[:, width:].cpu().tolist()
            for i, p in enumerate(batch):
                for j in range(k):
                    ids = fresh[i * k + j]
                    stop = "cap"
                    for n, t in enumerate(ids):
                        if t in eos_ids:
                            stop = {eot_id: "eot"}.get(t, "other_eos")
                            ids = ids[:n]
                            break
                    else:
                        ids = [t for t in ids if t != pad_id]
                    text = tokenizer.decode(ids, skip_special_tokens=False)
                    retok = tokenizer(text, add_special_tokens=False)["input_ids"]
                    fh.write(json.dumps({
                        "id": p["id"], "sample": j, "text": text,
                        "new_tokens": len(ids), "stop": stop,
                        "terminated": stop == "eot",
                        "has_special": any(t in special for t in ids),
                        "retokenizes": retok == ids,
                    }, sort_keys=True) + "\n")
                    tokens_done += len(ids)
                seqs_done += k
            fh.flush()
            elapsed = time.time() - started
            print(f"[shard {args.shard}] batch {b + 1}/{len(batches)} k={k} "
                  f"width={width}: {seqs_done} seqs, {tokens_done / elapsed:.0f} "
                  f"new tok/s, {seqs_done / elapsed:.1f} seq/s", flush=True)


def summarise(args) -> dict:
    """Termination, length and caption rates, per source and for the chemistry slice."""
    from src.generalist.evaluate.text_behaviour import caption_shaped

    version_dir = os.path.join(args.out_root, args.version)
    prompts = {p["id"]: p for p in read_prompts(version_dir)}
    out_dir = os.path.join(version_dir, args.out_name)
    cells = collections.defaultdict(lambda: collections.Counter())
    lengths = collections.defaultdict(list)
    kept_per_prompt = collections.Counter()
    seen_prompts = set()
    for name in sorted(os.listdir(out_dir)):
        if not name.endswith(".jsonl"):
            continue
        with open(os.path.join(out_dir, name)) as fh:
            for line in fh:
                row = json.loads(line)
                prompt = prompts[row["id"]]
                seen_prompts.add(row["id"])
                for cell in ("all", prompt["source"],
                             "chem" if prompt["chem"] else "general",
                             f"role/{prompt['role']}"):
                    c = cells[cell]
                    c["samples"] += 1
                    c[f"stop/{row['stop']}"] += 1
                    c["has_special"] += row["has_special"]
                    c["retokenizes"] += row["retokenizes"]
                    c["empty"] += not row["text"].strip()
                    c["caption_shaped"] += caption_shaped(row["text"])
                    if row["terminated"]:
                        lengths[cell].append(row["new_tokens"] + prompt["prompt_tokens"])
                if row["terminated"] and row["text"].strip() and not row["has_special"]:
                    kept_per_prompt[row["id"]] += 1

    def pct(values, qs=(0.1, 0.5, 0.9, 0.99)):
        values = sorted(values)
        return [values[min(int(len(values) * q), len(values) - 1)] for q in qs] if values else []

    report = {}
    for cell, c in sorted(cells.items()):
        n = c["samples"]
        report[cell] = {
            "samples": n,
            "terminated": c["stop/eot"] / n,
            "stop": {k[5:]: v / n for k, v in c.items() if k.startswith("stop/")},
            "empty": c["empty"] / n, "caption_shaped": c["caption_shaped"] / n,
            "has_special": c["has_special"] / n, "retokenizes": c["retokenizes"] / n,
            "kept_tokens_p10_50_90_99": pct(lengths[cell]),
            "kept_tokens_mean": (sum(lengths[cell]) / len(lengths[cell])
                                 if lengths[cell] else None),
        }
    none_kept = [pid for pid in seen_prompts if not kept_per_prompt[pid]]
    report["prompts"] = {
        "with_answers": len(seen_prompts), "with_no_kept_answer": len(none_kept),
        "kept_answers_histogram": dict(collections.Counter(
            kept_per_prompt[pid] for pid in seen_prompts)),
    }
    with open(os.path.join(out_dir, "summary.json"), "w") as fh:
        json.dump(report, fh, indent=1)
    print(json.dumps(report, indent=1))
    return report


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--version", default="v1")
    p.add_argument("--out-root", default=OUT_ROOT)
    p.add_argument("--out-name", default="answers")
    p.add_argument("--limit", type=int, default=0,
                   help="a pilot: this many prompts, taken at a fixed stride")
    p.add_argument("--gpus", type=int, default=0,
                   help="launch one shard per GPU and wait for all of them")
    p.add_argument("--shard", type=int, default=0)
    p.add_argument("--num-shards", type=int, default=1)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--temperature", type=float, default=TEMPERATURE)
    p.add_argument("--top-p", type=float, default=TOP_P)
    p.add_argument("--max-new-tokens", type=int, default=MAX_NEW_TOKENS)
    p.add_argument("--sequences-per-batch", type=int, default=SEQUENCES_PER_BATCH)
    p.add_argument("--summarise", action="store_true")
    args = p.parse_args(argv)

    if args.summarise:
        summarise(args)
        return 0
    if args.gpus:
        # Slurm hands a job its devices as a list; shard i takes the i-th of them
        # rather than device i, which may not be this job's.
        visible = [d for d in os.environ.get("CUDA_VISIBLE_DEVICES", "").split(",") if d]
        devices = visible or [str(i) for i in range(args.gpus)]
        if len(devices) < args.gpus:
            raise SystemExit(f"--gpus {args.gpus} but only {devices} are visible")
        procs = []
        for shard in range(args.gpus):
            cmd = [sys.executable, os.path.abspath(__file__),
                   *[a for a in (argv if argv is not None else sys.argv[1:])],
                   "--gpus", "0", "--shard", str(shard), "--num-shards", str(args.gpus)]
            env = dict(os.environ, CUDA_VISIBLE_DEVICES=devices[shard])
            procs.append(subprocess.Popen(cmd, env=env))
        codes = [proc.wait() for proc in procs]
        print(f"shards exited {codes}")
        if any(codes):
            return 1
        summarise(args)
        return 0
    run_shard(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
